### ISSUE TITLE
Rootchain Milestone Goals

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-rootchain#58]
- [x] Transaction Exit test- @legengliu @laskdaf 
- [x] Two queues @hamdiallam 
- [x] Tracked Exits @legengliu @hamdiallam 
- [x] Finalize exit/revert @laskdaf 
- [x] SubmitBlock Optimization - @AdityaSripal 
- [x] Align interfaces with SideChain
