### ISSUE TITLE
Security Audit Milestone

### ISSUE THREAD

**Issue by AdityaSripal** [FourthState/plasma-mvp-rootchain#75]
- [x] Merge all compatibility changes to master - @laskdaf 
- [x] Implement exiting fees @legengliu 
- [x] Implement non-final block submission (see SubmitBlock optimization in plasma-research)
- [x] Include Tx position in exit struct and event
